### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by vdukhovni** [jwiegley/async-pool#17]
It has been quite some time since 0.9.0.2. Multiple commits since, perhaps time for a new release?

But I would also like to see this package in stackage (https://github.com/commercialhaskell/stackage/blob/master/README.md).

**Comment by jwiegley** [comment]
Sounds like a good idea to me.

**Comment by rycee** [comment]
Yeah, a release would be super! I'm really wanting to have the updated `mapConcurrently`! 🙂

**Comment by jwiegley** [comment]
Released 0.9.1.
