### ISSUE TITLE
mapConcurrently is not reliable

### ISSUE THREAD

**Issue by mwotton** [jwiegley/async-pool#7]
I wrote a little wrapper:

```
mapConcurrentlyBounded n f args = AsyncPool.withTaskGroup n $ \tg -> do
  AsyncPool.mapConcurrently tg f args
```

but it doesn't seem to work as expected

```
> mapConcurrentlyBounded 10 (\x -> threadDelay (x*100000) >> print x) [1..100]
```

This fails with an STM error.

```
mapConcurrentlyBounded :: Traversable t => Int -> (a1 -> IO a) -> t a1 -> IO (t a)
mapConcurrentlyBounded n f args = AsyncPool.withTaskGroup n $ \tg -> do
  AsyncPool.mapTasks tg (fmap f args)
```

works fine.

**Comment by expipiplus1** [comment]
This is still an issue.

Thank you for the workaround, @mwotton!

**Comment by jwiegley** [comment]
I'd say we redefine `mapConcurrently` to this version, then, rather than trying to use the `Concurrently` abstraction.

**Comment by jwiegley** [comment]
@mwotton PR opened.

**Comment by jwiegley** [comment]
A user on #haskell has claimed that this still breaks with the current version on Hackage, but is fixed by the suggested change, so more testing is needed.

**Comment by jwiegley** [comment]
@Infinisil Your problem is different from the original report. The difference here is that you're not doing anything in a thread.  Just calling `createTaskGroup` and then `mapTasks` is very different from what `withTaskGroup` is doing.

**Comment by jwiegley** [comment]
Namely, at some point you need to `runTaskGroup` for the tasks within it to execute.

**Comment by Infinisil** [comment]
Oh, sorry for that! Thanks for the information though, I didn't know that (I only read the functions docs, so maybe I've missed that)

**Comment by rycee** [comment]
Ran into this issue today 🙁

The fix for this never seem to have gotten into a release, would be great if one could be arranged and put on Hackage!

**Comment by jwiegley** [comment]
@rycee What was that fix exactly?

**Comment by rycee** [comment]
@jwiegley The latest version of async-pool on Hackage is 0.9.0.2 and its [implementation of mapConcurrently](https://hackage.haskell.org/package/async-pool-0.9.0.2/docs/src/Control-Concurrent-Async-Pool-Async.html#mapConcurrently) is still the problematic one causing errors:
```
λ> import Control.Concurrent.Async.Pool
λ> withTaskGroup 1 $ \tg -> mapConcurrently tg print [1, 2, 3]
1
*** Exception: thread blocked indefinitely in an STM transaction
```

The implementation of commit 96589a8baffc4aa697d906f51016cfecfd20d818 fixes the issue for me as well
```
λ> mapConcurrently' tg f = mapTasks tg . fmap f
λ> withTaskGroup 1 $ \tg -> mapConcurrently' tg print [1, 2, 3]
1
2
3
[(),(),()]
```
so I would love to see a new release being made that includes this commit.

**Comment by jwiegley** [comment]
@rycee Got it; will do!
